routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::post('/get-filtered-program', 'FrontController@getFilteredProgram');
Route::get('phone/verify', 'PhoneVerificationController@show')->name('phoneverification.notice');
Route::post('phone/verify', 'PhoneVerificationController@verify')->name('phoneverification.verify');


Auth::routes();

Route::prefix('admin')->group(function() {
    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout/', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('programs', 'Admin\ProgramController');
    Route::resource('dishes', 'Admin\DishController');
    Route::resource('coupons', 'Admin\CouponController');
    Route::resource('orders', 'Admin\OrderController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('slides', 'SliderController');
    Route::post('storeProgramDish', 'Admin\DishController@storeProgramDish');
    Route::post('unlinkProgramDish', 'Admin\DishController@unlinkProgramDish');
}) ;

Auth::routes();

Route::group(['middleware' => 'auth'], function()
{
    Route::post('new-order', 'LkController@newOrder')->middleware('verifiedphone');
    Route::get('order/{id?}', 'LkController@order')->middleware('verifiedphone');
    Route::get('profile', 'LkController@profile')->middleware('verifiedphone');
    Route::post('profile', 'LkController@profileUpdate')->middleware('verifiedphone');
    Route::get('orders-history', 'LkController@ordersHistory')->middleware('verifiedphone');
    Route::post('get-promocode', 'LkController@getPromocode')->middleware('verifiedphone');
    Route::post('update-order-data', 'LkController@updateOrderData')->middleware('verifiedphone');
    Route::post('get-coords', 'LkController@getGeoCoords');
});

app/Models/Program.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{

    public function dishes()
    {
        return $this->belongsToMany('App\Models\Dish', 'program_dishes')->withPivot('prg_day', 'prg_day_meal', 'id');
    }
}

app/Http/Controllers/Admin/ProgramController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Dish;
use App\Models\Program;
use App\Models\ProgramDish;
use Illuminate\Http\Request;

class ProgramController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Program::all();
        return view('admin.programs.index')->with(compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.programs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name'=>'required|max:255',
            'description'=>'required|max:500',
            'evd' => "required|in:750,1000,1500,2000,2500,3500",
            'duration' => 'required',
            'mpd' => 'required|integer|between:2,8',
            'price'=>'integer'
        ];

        $customMessages = [
            'name.max' => 'Поле название должно быть не больше 255 символов',
            'name.required' => 'Поле название не заполнено',
            'description.max' => 'Поле описание должно быть не больше 500 символов',
            'description.required' => 'Поле описание не заполнено',
            'mpd.between' => 'Число приемов пищи должно быть от 2 до 8',
            'mpd.integer' => 'Поле число приемов пищи должно быть числовым',
            'price.integer' => 'Поле цена должно быть числовым',
            'mpd.required' => 'Поле число приемов пищи не заполнено',
            'duration.required' => 'Выберите длительность программы'
        ];
        $request->validate($rules, $customMessages);
        $item = new Program();
        $item->name = $request->name;
        $item->evd = $request->evd;
        $item->duration = $request->duration;
        $item->description = $request->description;
        $item->mpd = $request->mpd;
        $item->price = $request->price;
        if($item->save())
        {
            for ($i=1; $i<=$item->duration; $i++){
                for ($j=1; $j<=$item->mpd; $j++){
                    $program_dish = new ProgramDish();
                    $program_dish->program_id = $item->id;
                    $program_dish->dish_id = 0;
                    $program_dish->prg_day = $i;
                    $program_dish->prg_day_meal = $j;
                    $program_dish->save();
                }
            }
        }

        return redirect(route('programs.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Program::find($id);
        $dishes = Dish::all();
        $program_dishes = ProgramDish::with('dish')->orderBy('prg_day')->where('program_id', $item->id)->get()->groupBy(function($item) {
            return $item->prg_day;
        });
        return view('admin.programs.edit')->with(['item'=>$item, 'program_dishes'=>$program_dishes, 'dishes'=>$dishes]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name'=>'max:255',
            'description'=>'required|max:500',
            'price'=>'integer'
        ];

        $customMessages = [
            'name.max' => 'Поле название должно быть не больше 255 символов',
            'price.integer' => 'Поле цена должно быть числовым',
            'description.max' => 'Поле описание должно быть не больше 500 символов',
        ];
        $request->validate($rules, $customMessages);
        $item = Program::find($id);
        $item->name = $request->name;
        $item->evd = $request->evd;
        $item->description = $request->description;
        $item->price = $request->price;
        $item->save();

        return redirect(route('programs.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Program::find($id)->delete();
        ProgramDish::where('program_id', $id)->delete();
        return redirect()->route('programs.index')
            ->with('success','Программа успешно удалена');
    }
}

app/Http/Controllers/ProgramController.php
<?php

namespace App\Http\Controllers;

use App\Models\Program;
use Illuminate\Http\Request;

class ProgramController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function show(Program $program)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function edit(Program $program)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Program $program)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Program  $program
     * @return \Illuminate\Http\Response
     */
    public function destroy(Program $program)
    {
        //
    }
}

resources/views/admin/programs/create.blade.php
@extends('adminlte::page')

@section('title', 'Наборы')
<div class="panel panel-default box box-primary">
    @section('content_header')
        <h1>Добавить программу</h1>
        <div class="panel-heading fa-pull-right">


        </div>
@stop

@section('content')

            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-8">
                        <!-- general form elements -->

                        <div class="card card-primary card-tabs">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form role="form" action="{{url('admin/programs')}}" method="post">
                                {{csrf_field()}}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="fa-pull-left" for="name">Название</label>
                                        <input name="name" type="text" class="form-control" id="name" placeholder="Название">
                                    </div>
                                    <div class="form-group">
                                        <label class="" for="description">Описание</label>
                                        <textarea  name="description" class="textarea" id="description" placeholder="Описание"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label class="fa-pull-left" for="evd">Энергетическая ценность в ккал</label>
                                        <select name="evd" class="form-control" id="evd">
                                            <option value="750">750</option>
                                            <option value="1000">1000</option>
                                            <option value="1500">1500</option>
                                            <option value="2000">2000</option>
                                            <option value="2500">2500</option>
                                            <option value="3500">3500</option>
                                        </select>
                                        {{--<input type="text" class="form-control" id="evd" placeholder="ЭЦД">--}}
                                    </div>
                                    <div class="form-group">
                                        <label class="fa-pull-left" for="exampleInputPassword1">Продолжительность в днях</label>
                                        <select name="duration" class="form-control" id="duration">
                                            <option value="2">2</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                            <option value="6">6</option>
                                            <option value="12">12</option>
                                            <option value="20">20</option>
                                            <option value="24">24</option>
                                            <option value="30">30</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="fa-pull-left" for="mpd">Число приемов пищи в день</label>
                                        <input name="mpd" type="text" class="form-control" id="mpd" placeholder="Число приемов">
                                    </div>

                                    <div class="form-group">
                                        <label class="fa-pull-left" for="price">Цена</label>
                                        <input required name="price" type="text" class="form-control" id="price" placeholder="Цена">
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Сохранить</button>
                                </div>
                            </form>
                        </div>


                        </div>

                </div>

            </div>

@stop

        @section('css')

            <link rel="stylesheet" href="{{asset('/vendor/summernote/summernote-bs4.css')}}">
        @stop

        @section('js')
            <script src="{{asset('/vendor/summernote/summernote-bs4.min.js')}}"></script>
            <script> $('#description').summernote(); </script>
        @stop

resources/views/admin/programs/edit.blade.php
@extends('adminlte::page')

@section('title', 'Наборы')
<div class="panel panel-default box box-primary" id="app">
    @section('content_header')
        <h1>Редактировать программу</h1>
        <div class="panel-heading fa-pull-right">


        </div>
    @stop

    @section('content')

        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-8">
                    <!-- general form elements -->

                    <div class="card card-primary card-tabs">
                        <div class="card-header p-0 pt-1 border-bottom-0">
                            <ul class="nav nav-tabs" id="custom-tabs-two-tab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="custom-tabs-two-home-tab" data-toggle="pill" href="#custom-tabs-two-home" role="tab" aria-controls="custom-tabs-two-home" aria-selected="false">Общее</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="custom-tabs-two-profile-tab" data-toggle="pill" href="#custom-tabs-two-profile" role="tab" aria-controls="custom-tabs-two-profile" aria-selected="false">Блюда</a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content" id="custom-tabs-two-tabContent">
                                <div class="tab-pane fade active show" id="custom-tabs-two-home" role="tabpanel" aria-labelledby="custom-tabs-two-home-tab">
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    <!-- form start -->
                                    {!! Form::open(['url' => 'admin/programs/'.$item->id, 'method' => 'put']) !!}

                                        {{csrf_field()}}
                                        <div class="card-body">
                                            <div class="form-group">
                                                <label class="fa-pull-left" for="name">Название</label>
                                               {!! Form::text('name', $item->name, ['class'=>'form-control', 'id'=>'name']) !!}
                                            </div>
                                            <div class="form-group">
                                                <label class="" for="description">Описание</label>
                                                <textarea name="description" class="textarea" id="description" placeholder="Описание">{{$item->description}}</textarea>
                                            </div>
                                            <div class="form-group">
                                                <label class="fa-pull-left" for="evd">Энергетическая ценность в ккал</label>
                                                {!! Form::select('evd', [750 => '750', 1000 => '1000',1500=>'1500',2000=>'2000',2500=>'2500',3500=>'3500'],
                                                $item->evd, ['class'=>'form-control', 'id'=>'evd','placeholder'=>'Выберите']) !!}

                                            </div>
                                            <div class="form-group">
                                                <label class="fa-pull-left" for="duration">Продолжительность в днях</label>
                                                {!! Form::select('duration', [2 => '2', 4 => '4',5=>'5',6=>'6',12=>'12',20=>'20',24=>'24',30=>'30'],
                                 $item->duration, ['class'=>'form-control', 'id'=>'duration','placeholder'=>'Выберите', 'disabled'=>true]) !!}
                                            </div>
                                            <div class="form-group">
                                                <label class="fa-pull-left" for="mpd">Число приемов пищи в день</label>
                                                {!! Form::text('mpd', $item->mpd, ['class'=>'form-control', 'id'=>'mpd', 'disabled'=>true]) !!}
                                            </div>

                                            <div class="form-group">
                                                <label class="fa-pull-left" for="price">Цена</label>
                                                {!! Form::text('price', $item->price, ['class'=>'form-control', 'id'=>'price']) !!}
                                            </div>
                                        </div>
                                        <!-- /.card-body -->

                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary">Сохранить</button>
                                        </div>
                                    {!! Form::close() !!}
                                </div>
                                <div class="tab-pane fade" id="custom-tabs-two-profile" role="tabpanel" aria-labelledby="custom-tabs-two-profile-tab">
                                    <div class="row">

                                    <div class="col-7 col-sm-9">

                                        <!-- The time line -->
                                        <div class="timeline">
                                        @foreach ($program_dishes as $day => $programs_list)
                                            <!-- timeline time label -->
                                            <div class="time-label">
                                                <span class="bg-red">День {{$day}}</span>
                                            </div>
                                            <!-- /.timeline-label -->
                                            @foreach ($programs_list as $program_dish)
                                            <!-- timeline item -->
                                            <div>
                                                <i class="fas fa-utensils bg-blue"></i>
                                                <div class="timeline-item">
                                                    <span>
                                         Прием пищи {{$program_dish->prg_day_meal}}
                                        </span>
                                                    @if($program_dish->dish)
                                                        <h3 class="timeline-header"><a href="{{url('admin/dishes/'.$program_dish->dish_id.'/edit')}}">{{$program_dish->dish->name}}</a></h3>
                                                        <div class="timeline-body row">
                                                            <div class="col-6">
                                                                <img src="{{asset('uploads/dishes'.'/'.$program_dish->dish->photo)}}">
                                                            </div>

                                                            <div class="col-6">
                                                                <a href="#" class="btn btn-danger">
                                                                    <i class="fas fa-trash">
                                                                    </i>
                                                                    Отвязать
                                                                </a>
                                                            </div>

                                                        </div>
                                                    @else
                                                        <div class="timeline-body">
                                                            <h3 class="timeline-header">Блюдо не выбрано</h3>
                                                        </div>
                                                    @endif
                                                </div>
                                            </div>
                                            @endforeach
                                            <!-- END timeline item -->
                                            @endforeach

                                            <div>
                                                <i class="fas fa-clock bg-gray"></i>
                                            </div>

                                        </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>

                </div>

            </div>

        </div>

    @stop

    @section('css')
        <link rel="stylesheet" href="{{asset('/vendor/summernote/summernote-bs4.css')}}">
    @stop

    @section('js')
        <script src="{{asset('/vendor/summernote/summernote-bs4.min.js')}}"></script>
        <script src="{{asset('/js/vue.min.js')}}"></script>
        <script src="{{asset('/js/axios.min.js')}}"></script>
        <script>
            var app = new Vue({
                el: '#app',
                data: {
                   selected_dishes:{!! $program_dishes->toJson() !!}
                },
                methods: {
                    storeProgramDishes(day, meal, dish_id) {
                        var self = this;
                        axios.post('/order/goToPrint', {
                            order_id: order.id
                        })
                            .then(function (response) {
                                if (response.data.result === 'success') {
                                    console.log(response);
                                    toastr.success('Заказ принят в работу', '');
                                    // event.target.textContent = response.data.item.designphase.user.name+', '+response.data.item.designphase.created_at;

                                    // Vue.set(self.new_orders, 'activephase', response.data.new_orders);
                                }
                            })
                            .catch(function (error) {
                                console.log(error);
                            });
                    },
                }
            });

            $('#description').summernote();
        </script>
@stop

resources/views/admin/programs/index.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary">
@section('content_header')
    <h1>Программы</h1>
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">

            </div>
            <ul class="nav navbar-nav">
                <li> <a href="{{url('/admin/programs/create')}}" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Добавить
                    </a></li>
            </ul>
        </nav>
        {{--<div class="panel-heading fa-pull-right">--}}
            {{--<a href="{{url('/admin/programs/create')}}" class="btn btn-primary">--}}
                {{--<i class="fa fa-plus"></i> Добавить--}}
            {{--</a>--}}


        {{--</div>--}}
@stop

@section('content')

    <table id="example2" class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Название</th>
            <th>ЭЦД, Ккал</th>
            <th>Длительность, д.</th>
            <th>Число приемов</th>
            <th>Цена, ₽</th>
            <th>Описание</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach($items as $item)
        <tr>
            <td>{{$item->name}}</td>
            <td>{{$item->evd}}</td>
            <td>{{$item->duration}}</td>
            <td>{{$item->mpd}}</td>
            <td>{{$item->price}}</td>
            <td>{!! $item->description !!}</td>
            <td>
                <form class="delete" action="{{ route('programs.destroy',$item->id) }}" method="POST">

                    <a href="{{url('admin/programs/'.$item->id.'/edit')}}" class="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i></a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger btn-sm" onsubmit="confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
                </form>
            </td>
        </tr>
            @endforeach
        </tbody>
    </table>

@stop
</div>

@section('js')
    <script>
        $(".delete").on("submit", function(){
            return confirm("Удалить набор?");
        });

    </script>
@stop