routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::post('/get-filtered-program', 'FrontController@getFilteredProgram');
Route::get('phone/verify', 'PhoneVerificationController@show')->name('phoneverification.notice');
Route::post('phone/verify', 'PhoneVerificationController@verify')->name('phoneverification.verify');


Auth::routes();

Route::prefix('admin')->group(function() {
    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout/', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('programs', 'Admin\ProgramController');
    Route::resource('dishes', 'Admin\DishController');
    Route::resource('coupons', 'Admin\CouponController');
    Route::resource('orders', 'Admin\OrderController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('slides', 'SliderController');
    Route::post('storeProgramDish', 'Admin\DishController@storeProgramDish');
    Route::post('unlinkProgramDish', 'Admin\DishController@unlinkProgramDish');
}) ;

Auth::routes();

Route::group(['middleware' => 'auth'], function()
{
    Route::post('new-order', 'LkController@newOrder')->middleware('verifiedphone');
    Route::get('order/{id?}', 'LkController@order')->middleware('verifiedphone');
    Route::get('profile', 'LkController@profile')->middleware('verifiedphone');
    Route::post('profile', 'LkController@profileUpdate')->middleware('verifiedphone');
    Route::get('orders-history', 'LkController@ordersHistory')->middleware('verifiedphone');
    Route::post('get-promocode', 'LkController@getPromocode')->middleware('verifiedphone');
    Route::post('update-order-data', 'LkController@updateOrderData')->middleware('verifiedphone');
    Route::post('get-coords', 'LkController@getGeoCoords');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'phone', 'password','sms_code'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'phone_verified_at' => 'datetime',
        'birthday' => 'date'
    ];

    public function username(){
        return "phone";
    }

    public function hasVerifiedPhone()
    {
        return ! is_null($this->phone_verified_at);
    }

    public function markPhoneAsVerified()
    {
        return $this->forceFill([
            'phone_verified_at' => $this->freshTimestamp(),
        ])->save();
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = User::all();
        return view('admin.users.index')->with(compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
            ->with('success','Пользователь успешно удален');
    }
}

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary">
    @section('content_header')
        <h1>Пользователи</h1>
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">

            </div>
        </nav>
    @stop

    @section('content')

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>Телефон</th>
                <th>Имя
                <th>Пол</th>
                <th>Почта</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($items as $item)
                <tr>
                    <td>{{$item->phone}}</td>
                    <td>{!! $item->name !!}</td>
                    <td>{!! $item->gender !!}</td>
                    <td>{!! $item->email !!}</td>
                    <td>
                        <form class="delete" action="{{ route('users.destroy',$item->id) }}" method="POST">

                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    @stop
</div>

@section('js')
    <script>
        $(".delete").on("submit", function(){
            return confirm("Удалить пользователя?");
        });

    </script>
@stop