routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::post('/get-filtered-program', 'FrontController@getFilteredProgram');
Route::get('phone/verify', 'PhoneVerificationController@show')->name('phoneverification.notice');
Route::post('phone/verify', 'PhoneVerificationController@verify')->name('phoneverification.verify');


Auth::routes();

Route::prefix('admin')->group(function() {
    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout/', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('programs', 'Admin\ProgramController');
    Route::resource('dishes', 'Admin\DishController');
    Route::resource('coupons', 'Admin\CouponController');
    Route::resource('orders', 'Admin\OrderController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('slides', 'SliderController');
    Route::post('storeProgramDish', 'Admin\DishController@storeProgramDish');
    Route::post('unlinkProgramDish', 'Admin\DishController@unlinkProgramDish');
}) ;

Auth::routes();

Route::group(['middleware' => 'auth'], function()
{
    Route::post('new-order', 'LkController@newOrder')->middleware('verifiedphone');
    Route::get('order/{id?}', 'LkController@order')->middleware('verifiedphone');
    Route::get('profile', 'LkController@profile')->middleware('verifiedphone');
    Route::post('profile', 'LkController@profileUpdate')->middleware('verifiedphone');
    Route::get('orders-history', 'LkController@ordersHistory')->middleware('verifiedphone');
    Route::post('get-promocode', 'LkController@getPromocode')->middleware('verifiedphone');
    Route::post('update-order-data', 'LkController@updateOrderData')->middleware('verifiedphone');
    Route::post('get-coords', 'LkController@getGeoCoords');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function program()
    {
        return $this->belongsTo('App\Models\Program');
    }

    public function statuses()
    {
        return $this->hasMany('App\Models\OrderStatusHistory', 'order_id', 'id')->orderByDesc('created_at');
    }

    public function coupon()
    {
        return $this->hasOne('App\Models\Coupon', 'promocode', 'promocode');
    }


}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderStatusHistory;
use Carbon\Carbon;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Order::all();
        return view('admin.orders.index')->with(compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Order::find($id);

        return view('admin.orders.edit')->with(compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);

        $order->delivery_date = Carbon::parse( $request->delivery_date)->format('Y-m-d');
        $order->delivery_period = $request->delivery_period;
        $order->address = $request->address;
        $order->note = $request->note;
        $order->delivery_note = $request->delivery_note;
        $order->payment_type = $request->payment_type;
        $order->price = $request->price;
        $order->delivery_price = $request->delivery_price;
        if($order->save()){
            $order_status = OrderStatusHistory::create([
                'status_id'=>$request->status,
                'order_id'=>$order->id
            ]);
        }
        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Order::find($id)->delete();
        return redirect()->route('orders.index')
            ->with('success','Заказ успешно удален');
    }
}

resources/views/admin/orders/edit.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary" id="app">
    @section('content_header')
        <h1>Редактировать заказ</h1>

        <div class="panel-heading">
            <h5>Заказ {{$item->name}} от {{\Carbon\Carbon::parse($item->created_at)->format('d.m.y')}} </h5>
        </div>
    @stop

    @section('content')

        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-8">
                    <!-- general form elements -->

                    <div class="card card-primary card-tabs">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form role="form" action="{{url('admin/orders/'.$item->id)}}" method="POST" enctype="multipart/form-data">
                            {{csrf_field()}}
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label class="fa-pull-left" for="promocode">Программа</label>
                                    <div class="input-group">
                                    <input disabled="" value="{{$item->program->name}}" name="promocode" type="text" class="form-control" id="promocode" placeholder="До 10 символов, без пробелов">
                                    <div class="input-group-append"><a href="{{url('admin/orders/'.$item->program->id.'/edit')}}" class="btn btn-info">Посмотреть</a></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="fa-pull-left" for="discount_amount">Цена программы</label>
                                    <input disabled="" value="{{$item->program->price}}" type="text" class="form-control" id="discount_amount">
                                </div>
                                <div class="row">
                                    <div class="col-3 ">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="delivery_count">Количество доставок</label>
                                            <input value="{{$item->delivery_count}}" name="delivery_count" type="text" class="form-control" id="delivery_count"/>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="single_delivery_price">Стоимость одной доставки</label>
                                            <input value="@if($item->delivery_count!=0){{$item->delivery_price/$item->delivery_count}}@else{{$item->delivery_price}}@endif" name="single_delivery_price" type="text" class="form-control" id="single_delivery_price">
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="delivery_price">Общая стоимость доставки</label>
                                            <input value="{{$item->delivery_price}}" name="delivery_price" type="text" class="form-control" id="delivery_price">
                                        </div>
                                    </div></div>
                                <div class="form-group">
                                    <label class="fa-pull-left" for="address">Адрес доставки</label>
                                    <input value="{{$item->address}}" name="address" type="text" class="form-control" id="address">
                                </div>
                                <div class="form-group">
                                    <label class="fa-pull-left" for="delivery_period">Период доставки</label>
{{--                                    <input value="{{$item->delivery_period}}" name="delivery_period" type="text" class="form-control" id="delivery_period">--}}
                                    <select name="delivery_period" class="form-control" id="delivery_period">
                                        <option value="9.00-14.00">9.00 - 14.00</option>
                                        <option value="10.00-14.00">10.00 - 14.00</option>
                                        <option value="11.00-14.00">11.00 - 14.00</option>
                                    </select>
                                </div>
                                <div class="row">
                                    <div class="col-3 ">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="price">Стоимость заказа</label>
                                            <input value="{{$item->program->price+$item->delivery_price}}" name="price" type="text" class="form-control" id="price"/>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="promocode">Промокод</label>
                                            <input disabled="disabled" value="{{$item->promocode}}" name="promocode" type="text" class="form-control" id="promocode">
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="discount_amount">Скидка по промокоду в %</label>
                                            <input disabled="disabled" value="@if($item->coupon){{$item->coupon->discount_amount}}@endif" name="discount_amount" type="text" class="form-control" id="discount_amount">
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="final_price">Стоимость заказа со скидкой</label>
                                            <input value="{{$item->price}}" name="final_price" type="text" class="form-control" id="final_price">
                                        </div>
                                    </div></div>
                                <div class="row">
                                    <div class="col-4">
                                <div class="form-group">
                                    <label class="fa-pull-left" for="discount_amount">Предоплачено</label>
                                    <input value="" name="discount_amount" type="text" class="form-control" id="discount_amount">
                                </div></div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label class="fa-pull-left" for="discount_amount">Осталось оплатить</label>
                                            <input value="" name="discount_amount" type="text" class="form-control" id="discount_amount">
                                        </div></div></div>
                                <div class="form-group">
                                    <label class="" for="delivery_note">Примечание заказчика</label>
                                    <textarea name="delivery_note" class="textarea" id="delivery_note">{{$item->delivery_note}}</textarea>
                                </div>
                                <div class="form-group">
                                    <label class="" for="note">Примечание менеджера</label>
                                    <textarea name="note" class="textarea" id="note">{{$item->note}}</textarea>
                                </div>
                                <div class="form-group">
                                    <label class="">Способ оплаты</label>
                                    <div class="form-check">
                                        <input @if($item->payment_type=='prepay') checked @endif name="payment_type" class="form-check-input" type="radio" value="prepay" >
                                        <label class="form-check-label">Безнал сейчас</label>
                                    </div>
                                    <div class="form-check">
                                        <input @if($item->payment_type=='postpay') checked @endif name="payment_type" class="form-check-input" type="radio"value="postpay"  >
                                        <label class="form-check-label">Курьеру безналом</label>
                                    </div>
                                    <div class="form-check">
                                        <input @if($item->payment_type=='cash') checked @endif name="payment_type" class="form-check-input" type="radio" value="cash" >
                                        <label class="form-check-label">Курьеру налом</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="fa-pull-left" for="status">Статус заказа</label>

                                    <select name="status" class="form-control" id="status">
                                        <option value="3">Не подтвержден</option>
                                        <option value="2">Подтвержден</option>
                                        <option value="4">Доставка</option>
                                        <option value="5">Доставлен</option>
                                        <option value="6">Закрыт</option>
                                    </select>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>


    @stop


        @section('css')

            <link rel="stylesheet" href="{{asset('/vendor/air/css/datepicker.css')}}">
        @stop

        @section('js')

            <script src="{{asset('/vendor/air/js/datepicker.js')}}"></script>
            <script>

                $('#datepicker').datepicker({dateFormat: "yyyy-mm-dd"});

            </script>
@stop

resources/views/admin/orders/index.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary">
    @section('content_header')
        <h1>Заказы</h1>
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">

            </div>
            <ul class="nav navbar-nav">
                <li> <a href="{{url('/admin/orders/create')}}" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Добавить
                    </a></li>
            </ul>
        </nav>
    @stop

    @section('content')

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>Имя</th>
                <th>Оплачен</th>
                <th>Дата доставки</th>
                <th>Период доставки</th>
                <th>Цена</th>
                <th>Промокод</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($items as $item)
                <tr>
                    <td>{{$item->name}}-{{\Carbon\Carbon::parse($item->created_at)->format('d.m.y')}}</td>
                    <td>{!! $item->payment_status !!}</td>
                    <td>{!! $item->delivery_date !!}</td>
                    <td>{!! $item->delivery_period !!}</td>
                    <td>{!! $item->price !!}</td>
                    <td>{!! $item->promocode !!}</td>
                    <td>{{$item->statuses->first()->status->name}}</td>
                    <td>
                        <form class="delete" action="{{ route('orders.destroy',$item->id) }}" method="POST">

                            <a href="{{url('admin/orders/'.$item->id.'/edit')}}" class="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i></a>

                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    @stop
</div>

@section('js')
    <script>
        $(".delete").on("submit", function(){
            return confirm("Удалить заказ?");
        });

    </script>
@stop