routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::post('/get-filtered-program', 'FrontController@getFilteredProgram');
Route::get('phone/verify', 'PhoneVerificationController@show')->name('phoneverification.notice');
Route::post('phone/verify', 'PhoneVerificationController@verify')->name('phoneverification.verify');


Auth::routes();

Route::prefix('admin')->group(function() {
    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('logout/', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::resource('programs', 'Admin\ProgramController');
    Route::resource('dishes', 'Admin\DishController');
    Route::resource('coupons', 'Admin\CouponController');
    Route::resource('orders', 'Admin\OrderController');
    Route::resource('users', 'Admin\UserController');
    Route::resource('slides', 'SliderController');
    Route::post('storeProgramDish', 'Admin\DishController@storeProgramDish');
    Route::post('unlinkProgramDish', 'Admin\DishController@unlinkProgramDish');
}) ;

Auth::routes();

Route::group(['middleware' => 'auth'], function()
{
    Route::post('new-order', 'LkController@newOrder')->middleware('verifiedphone');
    Route::get('order/{id?}', 'LkController@order')->middleware('verifiedphone');
    Route::get('profile', 'LkController@profile')->middleware('verifiedphone');
    Route::post('profile', 'LkController@profileUpdate')->middleware('verifiedphone');
    Route::get('orders-history', 'LkController@ordersHistory')->middleware('verifiedphone');
    Route::post('get-promocode', 'LkController@getPromocode')->middleware('verifiedphone');
    Route::post('update-order-data', 'LkController@updateOrderData')->middleware('verifiedphone');
    Route::post('get-coords', 'LkController@getGeoCoords');
});

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    //
}

app/Http/Controllers/Admin/CouponController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Coupon;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CouponController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Coupon::all();

        return view('admin.coupons.index')->with(compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.coupons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'promocode' => 'required|unique:coupons|max:255',
            'expiration_date' => 'required',
            'discount_amount' => 'required|integer|between:1,100',
        ]);
        $item = new Coupon();
        $item->promocode = $request->promocode;
        $item->expiration_date = Carbon::createFromFormat('Y-m-d', $request->expiration_date)->format('Y-m-d');
        $item->discount_amount = $request->discount_amount;
        $item->save();

        return redirect('admin/coupons');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Coupon::find($id);
        return view('admin.coupons.edit')->with(compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'promocode' => 'required|unique:coupons|max:255',
            'expiration_date' => 'required',
            'discount_amount' => 'required|integer|between:1,100',
        ]);
        $item = Coupon::find($id);
        $item->promocode = $request->promocode;
        $item->expiration_date = Carbon::createFromFormat('Y-m-d', $request->expiration_date)->format('Y-m-d');
        $item->discount_amount = $request->discount_amount;
        $item->save();

        return redirect('admin/coupons');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Coupon::find($id)->delete();
        return redirect()->route('coupons.index')
            ->with('success','Купон удален');
    }
}

resources/views/admin/coupons/create.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary">
    @section('content_header')
        <h1>Добавить купон</h1>
        <div class="panel-heading fa-pull-right">

        </div>
    @stop

    @section('content')

        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-8">
                    <!-- general form elements -->

                    <div class="card card-primary card-tabs">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form role="form" action="{{url('admin/coupons')}}" method="post" enctype="multipart/form-data">
                            {{csrf_field()}}
                            <div class="card-body">
                                <div class="form-group">
                                    <label class="fa-pull-left" for="promocode">Промокод</label>
                                    <input name="promocode" type="text" class="form-control" id="promocode" placeholder="До 10 символов, без пробелов">
                                </div>
                                <div class="form-group">
                                    <label class="fa-pull-left" for="discount_amount">Скидка в %</label>
                                    <input name="discount_amount" type="text" class="form-control" id="discount_amount" placeholder="Значение скидки в %">
                                </div>
                                <div class="form-group">

                                    <label>Срок истечения:</label>

                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text">
                                            <i class="far fa-calendar-alt"></i>
                                          </span>
                                        </div>
                                        <input type="text" name="expiration_date" class="form-control pull-right" id="datepicker" placeholder="Выберите дату">
                                    </div>
                                    <!-- /.input group -->
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>


                </div>

            </div>

        </div>

    @stop

    @section('css')

        <link rel="stylesheet" href="{{asset('/vendor/air/css/datepicker.css')}}">
    @stop

    @section('js')

        <script src="{{asset('/vendor/air/js/datepicker.js')}}"></script>
        <script>

            $('#datepicker').datepicker({dateFormat: "yyyy-mm-dd"});

        </script>
@stop

resources/views/admin/coupons/edit.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary" id="app">
    @section('content_header')
        <h1>Редактировать купон</h1>
        <div class="panel-heading fa-pull-right">

        </div>
    @stop

    @section('content')

        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-8">
                    <!-- general form elements -->

                    <div class="card card-primary card-tabs">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <form role="form" action="{{url('admin/coupons/'.$item->id)}}" method="POST" enctype="multipart/form-data">
                            {{csrf_field()}}
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label class="fa-pull-left" for="promocode">Промокод</label>
                                    <input value="{{$item->promocode}}" name="promocode" type="text" class="form-control" id="promocode" placeholder="До 10 символов, без пробелов">
                                </div>
                                <div class="form-group">
                                    <label class="fa-pull-left" for="discount_amount">Скидка в %</label>
                                    <input value="{{$item->discount_amount}}" name="discount_amount" type="text" class="form-control" id="discount_amount" placeholder="Значение скидки в %">
                                </div>
                                <div class="form-group">

                                    <label>Срок истечения:</label>

                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                          <span class="input-group-text">
                                            <i class="far fa-calendar-alt"></i>
                                          </span>
                                        </div>
                                        <input value="{{$item->expiration_date}}" type="text" name="expiration_date" class="form-control pull-right" id="datepicker" placeholder="Выберите дату">
                                    </div>
                                    <!-- /.input group -->
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>


    @stop


        @section('css')

            <link rel="stylesheet" href="{{asset('/vendor/air/css/datepicker.css')}}">
        @stop

        @section('js')

            <script src="{{asset('/vendor/air/js/datepicker.js')}}"></script>
            <script>

                $('#datepicker').datepicker({dateFormat: "yyyy-mm-dd"});

            </script>
@stop

resources/views/admin/coupons/index.blade.php
@extends('adminlte::page')

<div class="panel panel-default box box-primary">
    @section('content_header')
        <h1>Купоны</h1>
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">

            </div>
            <ul class="nav navbar-nav">
                <li> <a href="{{url('/admin/coupons/create')}}" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Добавить
                    </a></li>
            </ul>
        </nav>
    @stop

    @section('content')

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>Промокод</th>
                <th>Срок истечения</th>
                <th>Скидка</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($items as $item)
                <tr>
                    <td>{{$item->promocode}}</td>
                    <td>{!! $item->expiration_date !!}</td>
                    <td>{!! $item->discount_amount !!}</td>
                    <td>
                        <form class="delete" action="{{ route('coupons.destroy',$item->id) }}" method="POST">

                            <a href="{{url('admin/coupons/'.$item->id.'/edit')}}" class="btn btn-info btn-sm"><i class="fas fa-pencil-alt"></i></a>

                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    @stop
</div>

@section('js')
    <script src="{{asset('/vendor/summernote/summernote-bs4.min.js')}}"></script>
    <script>
        $(".delete").on("submit", function(){
            return confirm("Удалить купон?");
        });

    </script>
@stop